##Introduction

This notebook will be used to write versions of the Euler totient and the Carmichael function. These functions will be used for testing examples and comparing running time.

##Function Implementation

In [ ]:
def prime_factorization(n):
  """Computes the prime factorization of a number n."""
  factors = {}
  d = 2
  temp = n
  while d * d <= temp:
    while temp % d == 0:
      factors[d] = factors.get(d, 0) + 1
      temp //= d
    d += 1
  if temp > 1:
    factors[temp] = factors.get(temp, 0) + 1
  return factors

In [ ]:
def carmichael_function(n):
  """Calculates the Carmichael function λ(n)."""
  if n == 1: return 1

  factors = prime_factorization(n)

  # Calculate lambda for each prime power factor
  lambdas = []
  for p, k in factors.items():
    lambdas.append(carmichael_lambda_prime_power(p, k))

  # Compute the LCM of all individual lambdas
  result = 1
  for val in lambdas:
    result = lcm(result, val)
  return result

## Euler Totient Function Implementation

In [ ]:
import time
import ipywidgets as widgets
from IPython.display import display, clear_output
import pandas as pd
import random # Import the random module

def euler_totient_function(n):
  """Calculates Euler's totient function φ(n)."""
  if n == 0: return 0
  if n == 1: return 1

  factors = prime_factorization(n)
  result = n
  for p in factors.keys():
    result -= result // p
  return result

# Global variable to store Euler Totient results
global_df_totient_results = pd.DataFrame()

# Demonstration with ipywidgets for a range
start_num_input_totient = widgets.Text(
    value='1',
    placeholder='Enter start number',
    description='Start Number:',
    disabled=False
)

end_num_input_totient = widgets.Text(
    value='10',
    placeholder='Enter end number',
    description='End Number:',
    disabled=False
)

num_runs_input_totient = widgets.Text(
    value='1',
    placeholder='Enter number of runs',
    description='Number of Runs:',
    disabled=False
)

button_totient = widgets.Button(description="Calculate Euler Totient for Range")
output_widget_totient = widgets.Output()

def on_button_totient_click(b):
    global global_df_totient_results # Declare intent to modify the global variable
    with output_widget_totient:
        clear_output()
        try:
            start_num = int(start_num_input_totient.value)
            end_num = int(end_num_input_totient.value)
            num_runs = int(num_runs_input_totient.value)

            if start_num > end_num:
                print("Start number cannot be greater than end number.")
                return
            if num_runs <= 0:
                print("Number of runs must be a positive integer.")
                return

            results = []
            # Create a list of numbers and shuffle it for random processing order
            numbers_to_process = list(range(start_num, end_num + 1))
            random.shuffle(numbers_to_process)

            for num in numbers_to_process:
                total_time = 0
                for _ in range(num_runs):
                    start_time = time.perf_counter()
                    totient_val = euler_totient_function(num)
                    end_time = time.perf_counter()
                    total_time += (end_time - start_time)

                average_time = total_time / num_runs
                results.append({'Number': num, 'Totient Value': totient_val, 'Average Time (s)': average_time})

            # Sort results by 'Number' before creating the DataFrame for consistent output
            results.sort(key=lambda x: x['Number'])
            global_df_totient_results = pd.DataFrame(results) # Assign to global variable
            display(global_df_totient_results)
        except ValueError:
            print("Please enter valid integers for the range and number of runs.")

button_totient.on_click(on_button_totient_click)

display(start_num_input_totient, end_num_input_totient, num_runs_input_totient, button_totient, output_widget_totient)

Text(value='1', description='Start Number:', placeholder='Enter start number')

Text(value='10', description='End Number:', placeholder='Enter end number')

Text(value='1', description='Number of Runs:', placeholder='Enter number of runs')

Button(description='Calculate Euler Totient for Range', style=ButtonStyle())

Output()

In [ ]:
import time
import ipywidgets as widgets
from IPython.display import display, clear_output
import pandas as pd
import random # Import the random module

# Global variable to store Carmichael function results
global_df_carmichael_results = pd.DataFrame()

def carmichael_lambda_prime_power(p, k):
  """Calculates λ(p^k) for a prime p and exponent k."""
  if p == 2:
    if k == 1: return 1
    if k == 2: return 2
    if k >= 3: return 2**(k-2)
  else: # p is an odd prime
    return p**(k-1) * (p-1)

def gcd(a, b):
  """Calculates the Greatest Common Divider of two numbers using the Euclidean algorithm."""
  while b:
    a, b = b, a % b
  return a

def lcm(a, b):
  """Calculates the Least Common Multiple of two numbers."""
  if a == 0 or b == 0: return 0
  return abs(a * b) // gcd(a, b)




# Demonstration with ipywidgets for Carmichael function over a range
start_num_input_carmichael = widgets.Text(
    value='1',
    placeholder='Enter start number',
    description='Start Number:',
    disabled=False
)

end_num_input_carmichael = widgets.Text(
    value='10',
    placeholder='Enter end number',
    description='End Number:',
    disabled=False
)

num_runs_input_carmichael = widgets.Text(
    value='1',
    placeholder='Enter number of runs',
    description='Number of Runs:',
    disabled=False
)

button_carmichael = widgets.Button(description="Calculate Carmichael Function for Range")
output_widget_carmichael = widgets.Output()

def on_button_carmichael_click(b):
    global global_df_carmichael_results # Declare intent to modify the global variable
    with output_widget_carmichael:
        clear_output()
        try:
            start_num = int(start_num_input_carmichael.value)
            end_num = int(end_num_input_carmichael.value)
            num_runs = int(num_runs_input_carmichael.value)

            if start_num > end_num:
                print("Start number cannot be greater than end number.")
                return
            if num_runs <= 0:
                print("Number of runs must be a positive integer.")
                return

            results = []
            # Create a list of numbers and shuffle it for random processing order
            numbers_to_process = list(range(start_num, end_num + 1))
            random.shuffle(numbers_to_process)

            for num in numbers_to_process:
                total_time = 0
                for _ in range(num_runs):
                    start_time = time.perf_counter()
                    carmichael_val = carmichael_function(num)
                    end_time = time.perf_counter()
                    total_time += (end_time - start_time)

                average_time = total_time / num_runs
                results.append({'Number': num, 'Carmichael Value': carmichael_val, 'Average Time (s)': average_time})

            # Sort results by 'Number' before creating the DataFrame for consistent output
            results.sort(key=lambda x: x['Number'])
            global_df_carmichael_results = pd.DataFrame(results) # Assign to global variable
            display(global_df_carmichael_results)
        except ValueError:
            print("Please enter valid integers for the range and number of runs.")

button_carmichael.on_click(on_button_carmichael_click)

display(start_num_input_carmichael, end_num_input_carmichael, num_runs_input_carmichael, button_carmichael, output_widget_carmichael)

Text(value='1', description='Start Number:', placeholder='Enter start number')

Text(value='10', description='End Number:', placeholder='Enter end number')

Text(value='1', description='Number of Runs:', placeholder='Enter number of runs')

Button(description='Calculate Carmichael Function for Range', style=ButtonStyle())

Output()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Exporting Results to CSV

To save the results from the Euler Totient and Carmichael function calculations, we can convert the pandas DataFrames into CSV files. These files can then be easily imported into spreadsheet applications like Microsoft Excel or Google Sheets.

In [ ]:
import pandas as pd
import os

# Ensure the calculation buttons for Euler Totient and Carmichael have been clicked
# to populate global_df_totient_results and global_df_carmichael_results.

if not global_df_totient_results.empty:
    euler_totient_filename = 'euler_totient_results.csv'
    global_df_totient_results.to_csv(euler_totient_filename, index=False)
    print(f'Euler Totient results saved to {euler_totient_filename}')
else:
    print('Euler Totient results DataFrame is empty. Please run the Euler Totient calculation first.')

if not global_df_carmichael_results.empty:
    carmichael_filename = 'carmichael_results.csv'
    global_df_carmichael_results.to_csv(carmichael_filename, index=False)
    print(f'Carmichael function results saved to {carmichael_filename}')
else:
    print('Carmichael function results DataFrame is empty. Please run the Carmichael calculation first.')

print('\nTo download these files, click on the folder icon on the left sidebar in Colab, then navigate to the current working directory (usually /content/) and right-click on the .csv files to download them.')

Euler Totient results saved to euler_totient_results.csv
Carmichael function results saved to carmichael_results.csv

To download these files, click on the folder icon on the left sidebar in Colab, then navigate to the current working directory (usually /content/) and right-click on the .csv files to download them.